# FROM php:8.2.7-apache@sha256:a55f0cfc97282f22ffe7b9840cf620a73cbc6e8a45a3f447b4f07eb0262eb884
FROM php:8.3-apache

# Criando usuário app.
ARG UID
ARG GID
ARG APP_PLATFORM
ARG APP_NODE_JS
ARG APP_SQL_SERVER
ARG APP_LARAVEL_PDF
ARG CACHE_BUST=1

ENV UID=${UID:-1000}
ENV GID=${GID:-1000}
ENV APP_PLATFORM=${APP_PLATFORM-x86}
ENV APP_NODE_JS=${APP_NODE_JS-true}
ENV APP_SQL_SERVER=${APP_SQL_SERVER-true}
ENV APP_LARAVEL_PDF=${APP_LARAVEL_PDF-true}
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
ENV CACHE_BUST=$CACHE_BUST

RUN addgroup --gid ${GID} --system app
RUN useradd -u ${UID} -g ${GID} -G 0,33 -s /bin/bash -m -d /home/app app

USER root

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

## Definindo tzdata pra poder definir o timezone pra não precisar de interação com o php.
RUN truncate -s0 /tmp/preseed.cfg; \
    echo "tzdata tzdata/Areas select America" >> /tmp/preseed.cfg; \
    echo "tzdata tzdata/Zones/America select Sao_Paulo" >> /tmp/preseed.cfg; \
    debconf-set-selections /tmp/preseed.cfg && \
    rm -f /etc/timezone /etc/localtime
RUN apt-get update && \
    apt-get install -y tzdata cron supervisor default-mysql-client apt-utils

RUN apt-get update && \
    apt-get install -y libpng-dev \
    libwebp-dev \
    libjpeg62-turbo-dev \
    libxpm-dev \
    libfreetype6-dev \
    libbz2-dev \
    libonig-dev \
    libgd3 \
    libgd-dev \
    libxml2-dev \
    libzip-dev \
    libicu-dev \
    libpq-dev \
    wget vim unixodbc-dev gnupg unzip
    # freetds-common freetds-bin unixodbc && \    
RUN apt-get update && apt-get clean && rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-configure gd --with-freetype --with-webp --with-jpeg && \
    docker-php-ext-install mysqli pdo pdo_mysql gd bz2 zip mbstring exif intl bcmath pcntl && \
    docker-php-ext-install -j$(nproc) opcache && \
    docker-php-ext-enable mysqli pdo pdo_mysql && \
    docker-php-ext-enable sodium 

#Configurando cron
COPY conf/crontab /etc/cron.d/
RUN crontab /etc/cron.d/*

# Copie o arquivo cron para a pasta /etc/cron.d/
COPY conf/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
# Dê permissões adequadas ao arquivo cron
RUN chmod 755 /etc/supervisor/conf.d/supervisord.conf

# Copie o script de configuração
COPY docker/app/scripts/config.sh /usr/local/bin/config.sh
RUN chmod +x /usr/local/bin/config.sh
# Execute o script de configuração

RUN /usr/local/bin/config.sh 

# limpa apt
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Iniciando Apache
RUN a2enmod lbmethod_byrequests

# habilitando Vhost
RUN a2enmod rewrite && a2enmod proxy && a2dissite 000-default
# Removendo a pasta html (eu prefiro trabalhar na pasta www)
RUN rm -rf /var/www/html
# Criando diretório de logs de erro do PHP
RUN mkdir -m 755 /tmp/php
# Instalando o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www

EXPOSE 8000

# USER app

CMD ["/usr/bin/supervisord", "-n"]


