version: '3.7'
#docker pull php:apache
networks:
  localhost:

services:
  apache-php: 
    build: docker/apache
    container_name: apache_php
    ports: 
      - "80:80"
    volumes:
      - ./conf/apache/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
      - ./www:/var/www:rw
      - ./conf/apache/vhost/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./logs:/tmp
    environment:
      - TZ=America/Sao_Paulo
      - APACHE_LOG_DIR=/tmp
      - INSTALL_DIR=/var/www
    networks:
      - localhost

      
