version: '3.7'

networks:
  localhost:
    driver: 'bridge'

services:
  app:     
    build: 
      context: ./
      dockerfile: docker/app/Dockerfile.php.8.3      
    container_name: app        
    tty: true      
    ports: 
      - "80:80"
      - "9000:9000"
      - "8000:8000"
      - "9001:9001"
    volumes:
      - ./conf/apache/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./conf/apache/ssl/openssl.cnf:/etc/ssl/openssl.cnf
      - ./www:/var/www:rw
      - ./conf/apache/vhost:/etc/apache2/sites-enabled
      - ./conf/ubuntu/bashrc.bash:/root/.bashrc
      - ./conf/ubuntu/bashrc.bash:/home/app/.bashrc      
      - ./conf/ubuntu/bash_history:/home/app/.bash_history:rw
      - ./conf/ubuntu/bash_history:/root/.bash_history:rw
      - ./logs/apache:/var/log/apache2
      - ./logs/php:/tmp/php
      - ./logs/cron:/var/log/cron
    environment:
      - TZ=America/Sao_Paulo
      - APACHE_LOG_DIR=/tmp
      - INSTALL_DIR=/var/www
    networks:
      - localhost
    # depends_on:
    #   - mysql_db

  mysql_db:
    build: docker/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: mysql_db
    #restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata/dbdata:/var/lib/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/config-file.cnf
    environment:      
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
    networks:
      - localhost

  phpmyadmin:
    build: docker/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql_db
    #restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql_db
      - PMA_PORT=3306
      - PMA_ARBITRARY=0
      - UPLOAD_LIMIT=128M
    networks:
      - localhost
    depends_on:
      - mysql_db

      
