version: '3.7'
#docker pull php:apache
networks:
  localhost:
    driver: 'bridge'

services:
  app: 
    build: docker/apache
    container_name: app
    tty: true  
    ports: 
      - "80:80"
      - "9000:9000"
      - "8000:8000"
      - "9001:9001"
    volumes:
      - ./conf/apache/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
      - ./www:/var/www:rw
      - ./conf/apache/vhost/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      #- ./logs:/tmp
    environment:
      - TZ=America/Sao_Paulo
      - APACHE_LOG_DIR=/tmp
      - INSTALL_DIR=/var/www
    networks:
      - localhost
    # depends_on:
    #   - mysql_db

  # mysql_db:
  #   build: docker/mysql
  #   command: mysqld --default-authentication-plugin=mysql_native_password
  #   container_name: mysql_db
  #   #restart: always
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./dbdata/dbdata:/var/lib/mysql
  #     - ./conf/mysql/my.cnf:/etc/mysql/conf.d/config-file.cnf
  #   environment:      
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_USER=bull
  #     - MYSQL_PASSWORD=bull
  #     - TZ=America/Sao_Paulo
  #   networks:
  #     - localhost

  # phpmyadmin:
  #   build: docker/phpmyadmin
  #   container_name: phpmyadmin
  #   links:
  #     - mysql_db
  #   #restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_HOST=mysql_db
  #     - PMA_PORT=3306
  #     - PMA_ARBITRARY=0
  #   networks:
  #     - localhost
  #   depends_on:
  #     - mysql_db

      
